#!/usr/bin/env python3
# Script to generate the glue code of a runtime loadable mcu module
#
# Copyright (C) 2026  Maksim Bolgov <maksim8024@gmail.com>
#
# This file may be distributed under the terms of the GNU GPLv3 license.
import sys, os, optparse, json, struct
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
import buildcommands
from buildcommands import error, msgproto

FILEHEADER = """
/* DO NOT EDIT! This is an autogenerated file. See scripts/buildmodule.py. */

#include "board/irq.h"
#include "board/pgm.h"
#include "command.h"
#include "compiler.h"
#include "loader.h"
"""

# Convert a data dictionary msgid to the "encoded" msgid used in C code
def encode_msgid(msgid):
    out = []
    msgproto.PT_int32().encode(out, msgid)
    if len(out) == 1:
        return out[0]
    if len(out) != 2:
        error("Unsupported message id %d" % (msgid,))
    return ((out[0] & 0x7f) << 7) | out[1]


######################################################################
# Handlers for module compile time requests
######################################################################

MODULE_CALL_LISTS = ['ctr_run_initfuncs', 'ctr_run_taskfuncs',
                     'ctr_run_shutdownfuncs']

# DECL_INIT, DECL_TASK, and DECL_SHUTDOWN support
class HandleModuleCallList(buildcommands.HandleCallList):
    def __init__(self):
        buildcommands.HandleCallList.__init__(self)
        for funcname in MODULE_CALL_LISTS:
            self.call_lists.setdefault(funcname, [])
    def decl_calllist(self, req):
        funcname = req.split()[1]
        if funcname not in MODULE_CALL_LISTS:
            error("Call list '%s' not supported in loadable modules"
                  % (funcname,))
        buildcommands.HandleCallList.decl_calllist(self, req)
    def get_used_call_lists(self):
        return [n for n in MODULE_CALL_LISTS if self.call_lists[n]]

# Static strings (reuse firmware ids) and enumerations
class HandleModuleEnumerations(buildcommands.HandleEnumerations):
    def __init__(self, fwdict):
        buildcommands.HandleEnumerations.__init__(self)
        self.fw_enums = fwdict.get('enumerations', {})
        self.static_string_ids = dict(self.fw_enums.get('static_string_id',
                                                        {}))
        self.new_static_strings = {}
    def add_enumeration(self, enum, name, value):
        fwvalue = self.fw_enums.get(enum, {}).get(name)
        if fwvalue is not None and fwvalue != value:
            error("Enumeration '%s %s' conflicts with firmware" % (enum, name))
        buildcommands.HandleEnumerations.add_enumeration(self, enum, name,
                                                         value)
    def assign_static_strings(self):
        next_id = max([buildcommands.STATIC_STRING_MIN - 1]
                      + list(self.static_string_ids.values())) + 1
        for s in self.static_strings:
            if s in self.static_string_ids:
                continue
            if next_id >= 0xff:
                error("Too many static strings")
            self.static_string_ids[s] = self.new_static_strings[s] = next_id
            next_id += 1
    def update_data_dictionary(self, data):
        enums = dict(self.enumerations)
        if self.new_static_strings:
            enums['static_string_id'] = dict(self.new_static_strings)
        if enums:
            data['enumerations'] = enums
    def generate_code(self, options):
        self.assign_static_strings()
        code = []
        for s in self.static_strings:
            code.append('    if (__builtin_strcmp(str, "%s") == 0)\n'
                        '        return %d;\n' % (s, self.static_string_ids[s]))
        fmt = """
uint8_t __always_inline
ctr_lookup_static_string(const char *str)
{
    %s
    return 0xff;
}
"""
        return fmt % ("".join(code).strip(),)

# Constants declared by the module
class HandleModuleConstants(buildcommands.HandleConstants):
    def __init__(self, fwdict):
        buildcommands.HandleConstants.__init__(self)
        self.fw_config = fwdict.get('config', {})
    def set_value(self, name, value):
        if name in self.fw_config and self.fw_config[name] != value:
            error("Constant '%s' conflicts with firmware" % (name,))
        buildcommands.HandleConstants.set_value(self, name, value)
    def update_data_dictionary(self, data):
        if self.constants:
            data['config'] = self.constants

# Commands and responses (new message ids follow the firmware ids)
class HandleModuleCommands(buildcommands.HandleCommandGeneration):
    def __init__(self, fwdict):
        buildcommands.HandleCommandGeneration.__init__(self)
        fw_messages = {}
        for key in ['commands', 'responses', 'output']:
            fw_messages.update(fwdict.get(key, {}))
        self.fw_names = {msg.split()[0]: msg
                         for key in ['commands', 'responses']
                         for msg in fwdict.get(key, {})}
        self.msg_to_encid = {msg: encode_msgid(msgid)
                             for msg, msgid in fw_messages.items()}
        self.messages_by_name = dict(self.fw_names)
        self.command_base = max(self.msg_to_encid.values()) + 1
        self.new_messages = []
    def decl_command(self, req):
        msgname = req.split()[3]
        if msgname in self.fw_names:
            error("Command '%s' is already implemented by the firmware"
                  % (msgname,))
        buildcommands.HandleCommandGeneration.decl_command(self, req)
    def create_message_ids(self):
        encoded_msgid = self.command_base - 1
        mlist = list(self.commands.keys()) + [m for n, m in self.encoders]
        for msgname in mlist:
            msg = self.messages_by_name.get(msgname, msgname)
            if msg not in self.msg_to_encid:
                encoded_msgid += 1
                self.msg_to_encid[msg] = encoded_msgid
                self.new_messages.append(msg)
        if encoded_msgid >= 1<<14:
            error("Too many message ids")
        self.encid_to_msgid = {
            encoded_msgid: self.convert_encoded_msgid(encoded_msgid)
            for encoded_msgid in self.msg_to_encid.values()
        }
    def update_data_dictionary(self, data):
        commands = set(self.messages_by_name[n] for n in self.commands)
        outputs = set(m for n, m in self.encoders if n is None)
        for msg in self.new_messages:
            msgid = self.encid_to_msgid[self.msg_to_encid[msg]]
            key = 'responses'
            if msg in commands:
                key = 'commands'
            elif msg in outputs:
                key = 'output'
            data.setdefault(key, {})[msg] = msgid
    def generate_commands_code(self):
        cmd_by_encid = {
            self.msg_to_encid[self.messages_by_name[msgname]]: cmd
            for msgname, cmd in self.commands.items()
        }
        if not cmd_by_encid:
            return ("\n#define MODULE_COMMANDS NULL\n"
                    "#define MODULE_COMMAND_COUNT 0\n")
        index = []
        externs = {}
        for encoded_msgid in range(self.command_base, max(cmd_by_encid) + 1):
            if encoded_msgid not in cmd_by_encid:
                index.append(" {\n},")
                continue
            funcname, flags, msgname = cmd_by_encid[encoded_msgid]
            msg = self.messages_by_name[msgname]
            externs[funcname] = 1
            parsercode = self.build_parser(encoded_msgid, msg, 'response')
            index.append(" {%s\n    .flags=%s,\n    .func=%s\n}," % (
                parsercode, flags, funcname))
        index = "".join(index).strip()
        externs = "\n".join(["extern void "+funcname+"(uint32_t*);"
                             for funcname in sorted(externs)])
        fmt = """
%s

static const struct command_parser module_command_index[] PROGMEM = {
%s
};

#define MODULE_COMMANDS module_command_index
#define MODULE_COMMAND_COUNT ARRAY_SIZE(module_command_index)
"""
        return fmt % (externs, index)


######################################################################
# Module image layout
######################################################################

HEADER_CODE = """
extern char _module_image_end[], _module_bss_start[], _module_bss_end[];
%s
const struct loader_module_header loader_module_header __visible
    __section(".loader_header") = {
    .magic = LOADER_MAGIC,
    .abi_version = LOADER_ABI_VERSION,
    .base = (void*)&loader_module_header,
    .image_end = _module_image_end,
    .bss_start = _module_bss_start,
    .bss_end = _module_bss_end,%s
    .commands = MODULE_COMMANDS,
    .command_base = %d,
    .command_count = MODULE_COMMAND_COUNT,
};
"""

LINKER_SCRIPT = """/* DO NOT EDIT! Autogenerated by scripts/buildmodule.py */

ENTRY(loader_module_header)

SECTIONS
{
    .text 0x%x : {
        KEEP(*(.loader_header))
        *(.text .text.*)
        *(.rodata .rodata.*)
        *(.data .data.*)
        . = ALIGN(8);
        _module_image_end = .;
    }
    .bss (NOLOAD) : {
        _module_bss_start = .;
        *(.bss .bss.*)
        *(COMMON)
        . = ALIGN(8);
        _module_bss_end = .;
    }
    /DISCARD/ : {
        *(.compile_time_request)
        *(.note .note.*)
        *(.comment)
        *(.ARM.exidx .ARM.exidx.* .ARM.extab .ARM.extab.*)
        *(.init .fini)
    }
}

/* Firmware functions exported by src/loader.c */
%s
"""

class HandleModuleLayout:
    def __init__(self, info, cmdgen, calllist):
        self.info = info
        self.cmdgen = cmdgen
        self.calllist = calllist
        self.ctr_dispatch = {}
    def update_data_dictionary(self, data):
        pass
    def generate_code(self, options):
        fields = {'ctr_run_initfuncs': 'run_initfuncs',
                  'ctr_run_taskfuncs': 'run_taskfuncs',
                  'ctr_run_shutdownfuncs': 'run_shutdownfuncs'}
        used = self.calllist.get_used_call_lists()
        decls = "".join(["void %s(void);\n" % (f,) for f in used])
        funcs = "".join(["\n    .%s = %s," % (fields[f], f) for f in used])
        return HEADER_CODE % (decls, funcs, self.cmdgen.command_base)
    def generate_linker_script(self):
        exports = self.info.get('exports', {})
        provides = ["PROVIDE(%s = 0x%x);" % (name, addr)
                    for name, addr in sorted(exports.items())]
        return LINKER_SCRIPT % (self.info['base'], "\n".join(provides))


######################################################################
# Linked image verification
######################################################################

SHF_ALLOC = 0x2

def read_str(data, offset):
    return data[offset:data.index(b'\0', offset)].decode()

# Read the section headers of a 32bit little-endian ELF file
def read_elf(filename):
    f = open(filename, 'rb')
    data = f.read()
    f.close()
    if data[:6] != b'\x7fELF\x01\x01':
        error("Not a 32bit little-endian ELF file")
    shoff, = struct.unpack_from('<I', data, 0x20)
    shentsize, shnum, shstrndx = struct.unpack_from('<HHH', data, 0x2e)
    fields = ['name', 'type', 'flags', 'addr', 'offset', 'size', 'link',
              'info', 'addralign', 'entsize']
    sections = [dict(zip(fields, struct.unpack_from('<10I', data,
                                                    shoff + i * shentsize)))
                for i in range(shnum)]
    stroff = sections[shstrndx]['offset']
    for sh in sections:
        sh['name'] = read_str(data, stroff + sh['name'])
    return data, sections

def check_elf(elf_filename, info):
    data, sections = read_elf(elf_filename)
    total_end = info['base']
    for sh in sections:
        if not sh['flags'] & SHF_ALLOC or not sh['size']:
            continue
        if sh['name'] not in ['.text', '.bss']:
            error("Unsupported section '%s' in loadable module"
                  % (sh['name'],))
        total_end = max(total_end, sh['addr'] + sh['size'])
    sys.stdout.write("Module size: %d bytes of ram\n"
                     % (total_end - info['base'],))


######################################################################
# Main code
######################################################################

def read_json(filename):
    f = open(filename, 'r')
    data = json.load(f)
    f.close()
    return data

def write_file(filename, data):
    f = open(filename, 'w')
    f.write(data)
    f.close()

def main():
    usage = "%prog [options] <cmd section file> <output.c>"
    opts = optparse.OptionParser(usage)
    opts.add_option("-d", dest="dictionary",
                    help="firmware data dictionary file")
    opts.add_option("-i", dest="info",
                    help="loader info file (module address and exports)")
    opts.add_option("-o", dest="write_dictionary",
                    help="file to write module data dictionary additions")
    opts.add_option("-l", dest="write_linker_script",
                    help="file to write module linker script")
    opts.add_option("-c", dest="check_elf",
                    help="verify a linked module elf file")
    options, args = opts.parse_args()
    if options.info is None:
        opts.error("Loader info file (-i) required")
    info = read_json(options.info)
    if options.check_elf:
        check_elf(options.check_elf, info)
        return
    if len(args) != 2 or options.dictionary is None:
        opts.error("Incorrect arguments")
    incmdfile, outcfile = args
    fwdict = read_json(options.dictionary)

    # Setup handlers
    calllist = HandleModuleCallList()
    cmdgen = HandleModuleCommands(fwdict)
    handlers = [calllist, HandleModuleEnumerations(fwdict),
                HandleModuleConstants(fwdict), cmdgen]
    layout = HandleModuleLayout(info, cmdgen, calllist)
    handlers.append(layout)

    # Parse request file
    ctr_dispatch = { k: v for h in handlers for k, v in h.ctr_dispatch.items() }
    f = open(incmdfile, 'r')
    data = f.read()
    f.close()
    for req in data.split('\n'):
        req = req.lstrip()
        if not req:
            continue
        cmd = req.split()[0]
        if cmd not in ctr_dispatch:
            error("Unknown build time command '%s'" % cmd)
        ctr_dispatch[cmd](req)

    # Write output
    code = "".join([FILEHEADER] + [h.generate_code(options) for h in handlers])
    write_file(outcfile, code)
    if options.write_linker_script:
        write_file(options.write_linker_script, layout.generate_linker_script())
    if options.write_dictionary:
        moddict = {}
        for h in handlers:
            h.update_data_dictionary(moddict)
        write_file(options.write_dictionary,
                   json.dumps(moddict, separators=(',', ':'), sort_keys=True))

if __name__ == '__main__':
    main()
